config/routes.rb
Myapp::Application.routes.draw do
  resources :cards
  get "cards/index"

  resources :decks
  get 'decks/index'
 
  

root to: 'cards#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
    mount_uploader :image, ImageUploader
end

app/models/deck.rb
class Deck < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end









  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end



  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @card = Card.find(params[:id])
    @card.destroy
   
    redirect_to cards_path
  end


  #def destroy
  #  @card.destroy
   # respond_to do |format|
  #    format.html { redirect_to cards_url }
   #   format.json { head :no_content }
  #  end
  #end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:cardID, :cardNumber, :setTotal, :setName, :cardName, :cardColour,:cardType, :powerTough, :castingCost, :cardText, :artist, :rarity, :decks, :image)
    end
end



#index
#show
#new
#edit
#create
#update
#destroy

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]
      
        # GET /cards
        # GET /cards.json
  def index
    @decks = Deck.all
  end
      
        # GET /cards/1
        # GET /cards/1.json
  def show
  end
      
   
  def new
    @deck = Deck.new
  end
      
  
  def edit
  end



  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'The Deck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deck }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'The Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
   
    redirect_to decks_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_deck
    @deck = Deck.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deck_params
    params.require(:deck).permit(:cardID, :deckID, :dateCreated, :deckName, :deckType, :deckDescription,:totalCards)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mainTitle = "Welcome in Inspinia Rails Seed Project"
    @mainDesc = "It is an application skeleton for a typical Ruby on Rails web app. You can use it to quickly bootstrap your webapp projects and dev/prod environment."
  end

  def minor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name, class_name = nil)
        if params[:controller] == controller_name
         class_name == nil ? "active" : class_name
        else
           nil
        end
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card, :html => { :multipart => true}) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


          <div class="ibox-content">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>
                            </th>
                            <th><%= f.label :cardNumber %><br><%= f.number_field :cardNumber %>
                            </th>
                             <th><%= f.label :cardColour %><br><%= f.text_field :cardColour %>
                            </th>
                        
                         </tr>
                         <tr>  
                            <th><%= f.label :cardName %><br><%= f.text_area :cardName %>
                            </th>
                            <th><%= f.label :setName %><br><%= f.text_area :setName %>
                            </th>
                            <th><%= f.label :cardType %><br><%= f.text_area :cardType %>
                            </th>

                         </tr>
                         <tr>
                            <th><%= f.label :powerTough %><br><%= f.text_area :powerTough %>
                            </th>   
                            <th><%= f.label :castingCost %><br><%= f.text_area :castingCost %>
                            </th>
                            <th><%= f.label :cardText %><br><%= f.text_area :cardText %>
                            </th>
                         </tr>
                         <tr>
                            <th> <%= f.label :artist %><br><%= f.text_area :artist %>
                            </th> 
                            <th> <%= f.label :rarity %><br><%= f.text_area :rarity %>
                            </th>
                                <th><%= f.label :setTotal %><br><%= f.number_field :setTotal %>
                            </th>
                         </tr>
                          <tr>
                            <th><button  class="btn btn-default btn-lg btn-block"><%= f.file_field :image %></button> 
                            </th> 
                            <th> 
                            </th>
                            <th><button  class="btn btn-default btn-lg btn-block"><%= f.submit %></button> 
                            </th>
                         </tr>
                        
                        </thead>
                    </table>
                </div>
                <% end %>



        

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>
<button type="button" class="btn btn-default btn-lg btn-block"><%= link_to 'New Card', new_card_path %></button>


<table class="border">
<thead>
    <tr>
      <th>table test</th>
    </tr>
</thead>
</table>




<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Card ID</th>
      <th>Card Name</th>
      <th>Card Colour</th>
      <th>Card Type</th>
      <th>Set Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.cardID %></td>
        <td><%= card.cardName %></td>
        <td><%= card.cardColour %></td>
        <td><%= card.cardType %></td>
        <td><%= card.setName %></td>
        <td><button type="button" class="btn btn-default btn-sml"><%= link_to 'Show', card %></td>
        <td><button type="button" class="btn btn-default btn-sml"><%= link_to 'Edit', edit_card_path(card) %></td>
         <td><button type="button" class="btn btn-default btn-sml"><%= button_to "Delete", card_path(:id => card.id), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>




<div class="wrapper wrapper-content">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1><%= @card.cardName %></h1>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">


<table>

<tr >
   <td class="img-pad"><%= image_tag @card.image_url.to_s%></td>
<td>

<table class="table table-bordered table-striped table-hover table-responsive">
  <tbody> 
    <tr>
      <td class="col col-lg-3">
        
      </td>
      <td>
        
      </td>
    </tr>
    <tr>
      <td>
       Card Number
      </td>
      <td>
        <%= @card.cardNumber %>
      </td>
    </tr>
    <tr>
      <td>
        Set Total
      </td>
      <td>
        <%= @card.setTotal %>
      </td>
    </tr>
    <tr>
      <td>
        Card Name
      </td>
      <td>
        <%= @card.cardName %>
      </td>
    </tr>
        <tr>
      <td>
        Card Colour
      </td>
      <td>
        <%= @card.cardColour %>
      </td>
    </tr>
    <tr>
      <td>
        Set Name
      </td>
      <td>
        <%= @card.setName %>
      </td>
    </tr>
    <tr>
      <td>
        Card Type
      </td>
            <td>
         <%= @card.cardType %>
      </td>
    <tr>
      <td>
        Power / Toughness
      </td>
      <td>
        <%= @card.powerTough %>
      </td>
    </tr>
    <tr>
      <td>
        Casting Cost
      </td>
      <td>
        <%= @card.castingCost %>
      </td>
    </tr>
    <tr>
      <td>
        Card Text
      </td>
      <td>
        <%= @card.cardText %>
      </td>
    </tr>
    <tr>
      <td>
        Artist
      </td>
      <td>
        <%= @card.artist %>
      </td>
    </tr>
    <tr>
      <td>
        Rarity
      </td>
      <td>
        <%= @card.rarity %>
      </td>
    </tr>
    <tr>
    <td></td>
      <td><button type="button" class="btn btn-default btn-sml"><%= link_to 'Edit', edit_card_path(@card) %>
      <button type="button" class="btn btn-default btn-sml"><%= link_to 'Back', cards_path %>
      

      </td>
    </tr>
  </tbody>
</table>

</td>
</tr>



</table>

app/views/decks/_form.html.erb
<%= form_for(@deck, :html => { :multipart => true}) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="ibox-content">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>


                         </tr>
                         <tr>  
                            <th><%= f.label :deckID %><br><%= f.text_area :deckID %>
                            </th>
                            <th><%= f.label :dateCreated %><br><%= f.text_area :dateCreated %>
                            </th>
                            <th><%= f.label :deckName %><br><%= f.text_area :deckName %>
                            </th>
                         </tr>
                         <tr>
                            <th><%= f.label :deckType %><br><%= f.text_area :deckType %>
                            </th>
                            <th><%= f.label :deckDescription %><br><%= f.text_area :deckDescription %>
                            </th>
                            <th><%= f.label :totalCards %><br><%= f.text_area :totalCards %>
                            </th>
                         </tr>

                          <tr>
                            <th><button  class="btn btn-default btn-lg btn-block"><%= f.submit %></button> 
                            </th> 
                            <th> 
                            </th>
                            <th>
                            </th>
                         </tr>
                        
                        </thead>
                    </table>
                    </div>
  <% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Decks</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Deck Name</th>
      <th colspan="4"></th>
    </tr>
        <tr>
      <th>Deck Name/th>
      <th>Deck Description</th>
      <th>Deck Type</th>
      <th>Date Created</th>
      <th>Total Cards</th>
      <th colspan="4"></th>
    </tr>
  </thead>


    <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.deckName %></td>
        <td><%= deck.deckDescription %></td>
        <td><%= deck.deckType %></td>
        <td><%= deck.dateCreated %></td>
        <td><%= deck.totalCards %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
         <td><%= button_to "delete", deck_path(:id => deck.id), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>
<button type="button" class="btn btn-default btn-lg btn-block"><%= link_to 'New Deck', new_deck_path %></button>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="wrapper wrapper-content">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h1><%= @deck.deckName %></h1>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">

<table>
<tr>
  <td>  
fdfdfdf
  </td>

<td>

<table class="table table-bordered table-striped table-hover table-responsive">
  <tbody> 
    <tr>
      <td class="col col-lg-3">
        Deck ID
      </td>
      <td>
        <%= @deck.deckID %>
      </td>
    </tr>
    <tr>
      <td>
       Date Created
      </td>
      <td>
        <%= @deck.dateCreated %>
      </td>
    </tr>
    <tr>
      <td>
        Deck Type
      </td>
      <td>
        <%= @deck.deckType %>
      </td>
    </tr>
    <tr>
      <td>
        Deck Name
      </td>
      <td>
        <%= @deck.deckName %>
      </td>
    </tr>
        <tr>
      <td>
        Deck Description
      </td>
      <td>
        <%= @deck.deckDescription %>
      </td>
    </tr>
    <tr>
      <td>
        Total Cards
      </td>
      <td>
        <%= @deck.totalCards %>
      </td>
    </tr>
    
    <tr>
    <td></td>
      <td><button type="button" class="btn btn-default btn-sml"><%= link_to 'Edit', edit_deck_path(@deck) %>
      <button type="button" class="btn btn-default btn-sml"><%= link_to 'Back', decks_path %></td>
    </tr>
  </tbody>
</table>
</td>
</tr>

</table>

app/views/home/another.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Third view
                </h1>
                <small>another view</small>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    <%= @mainTitle %>
                </h1>
                <small>
                    <%= @mainDesc %>
                </small>
            </div>
        </div>
    </div>
</div>

app/views/home/minor.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Simple example of second view
                </h1>
                <small>Configure in home_controller.rb as minor view.</small>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        "They're easy enough to find. Question is, are you sure you want to find one?"
    </div>
    <div>
        <strong>Copyright</strong> MTG Archive 2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Example user</strong>
                            </span> <span class="text-muted text-xs block">Example menu <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-laptop"></i> <span class="nav-label">Cards</span>
                <% end %>
            </li>
                <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/decks" do %>
                <i class="fa fa-laptop"></i> <span class="nav-label">Decks</span>
                <% end %>
            </li>
            <!--<li class="<%= 'active' if current_page?('/home/minor') %>">
                <%= link_to "/home/minor" do %>
                <i class="fa fa-desktop"></i> <span class="nav-label">Minor page</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/home/another') %>">
                <%= link_to "/home/another" do %>
                <i class="fa fa-desktop"></i> <span class="nav-label">Another</span>
                <% end %>
            </li>-->
        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MTG Archive</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

</body>
</html>